title: Kathleen Ma
email: klma@princeton.edu
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kathleenmachine
github_username: kathleenlma
kramdown:
  input: GFM
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
include: ['_pages']
collections:
  projects: 
    output: true
    permalink: /projects/:path/